# Generated by Django 5.2 on 2025-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtodo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
